#!/usr/bin/env python3
import argparse
import json
import sys
from pathlib import Path
from datetime import datetime, timezone

from multi_judge import MultiAgentCodeJudge


def generate_html_report(result: dict, file_path: str, model: str) -> str:
    now = datetime.now(timezone.utc).isoformat()
    verdict_text = "PASS ✅" if result["overall_pass"] else "FAIL ❌"

    blocking_html = ""
    if result["blocking_failures"]:
        blocking_html = (
            "<ul>"
            + "".join(f"<li>{b}</li>" for b in result["blocking_failures"])
            + "</ul>"
        )
    else:
        blocking_html = "<p class='muted'>None</p>"

    agent_blocks = ""
    for v in result["verdicts"]:
        issues_html = ""
        if v["issues"]:
            issues_html = "<ul>" + "".join(f"<li>{i}</li>" for i in v["issues"]) + "</ul>"
        else:
            issues_html = "<p class='muted'>None</p>"

        agent_blocks += f"""
        <div class="agent-card">
            <h3>{v['agent'].upper()}</h3>
            <p><strong>PASS:</strong> {v['pass']}</p>
            <p><strong>SCORE:</strong> {v['score']}</p>
            <p><strong>SUMMARY:</strong> {v['summary']}</p>
            <div class="issues">
                <strong>Issues:</strong>
                {issues_html}
            </div>
        </div>
        """

    html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Claude Code Judge Report</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica, Arial;
            background: #f5f7fa;
            color: #222;
        }}
        .container {{
            max-width: 900px;
            margin: 30px auto;
            background: #fff;
            padding: 25px 35px;
            border-radius: 10px;
            box-shadow: 0 5px 20px rgba(0,0,0,0.08);
        }}
        h1 {{
            margin-top: 0;
        }}
        .meta {{
            color: #555;
            font-size: 14px;
        }}
        .verdict {{
            font-size: 22px;
            font-weight: bold;
            margin-top: 15px;
        }}
        .score {{
            font-size: 18px;
            margin-top: 10px;
        }}
        .agent-card {{
            border: 1px solid #e1e4e8;
            border-radius: 8px;
            padding: 15px 20px;
            margin-top: 20px;
        }}
        .agent-card h3 {{
            margin-top: 0;
        }}
        .issues {{
            margin-top: 10px;
        }}
        .muted {{
            color: #888;
        }}
        .footer {{
            margin-top: 40px;
            font-size: 13px;
            color: #888;
            text-align: center;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Claude Code Judge Report</h1>

        <p class="meta"><strong>File:</strong> {file_path}</p>
        <p class="meta"><strong>Model:</strong> {model}</p>
        <p class="meta"><strong>Generated:</strong> {now}</p>

        <p class="verdict">Policy Verdict: {verdict_text}</p>

        <p class="score"><strong>Average Score:</strong> {result['average_score']}</p>

        <h2>Blocking Failures</h2>
        {blocking_html}

        <h2>Agent Verdicts</h2>
        {agent_blocks}

        <div class="footer">
            Generated by Claude Multi-Agent Code Judge
        </div>
    </div>
</body>
</html>
"""
    return html


def write_html_report(result: dict, file_path: str, model: str, output_path: str):
    html = generate_html_report(result, file_path, model)
    Path(output_path).write_text(html, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(
        description="Claude Multi-Agent Code Judge"
    )

    parser.add_argument("file", help="Python file to judge")

    parser.add_argument(
        "--model",
        default="claude-sonnet-4-20250514",
        help="Claude model to use"
    )

    parser.add_argument(
        "--json",
        action="store_true",
        help="Output raw JSON only"
    )

    parser.add_argument(
        "--ci",
        action="store_true",
        help="CI mode (JSON only, exit code only)"
    )

    parser.add_argument(
        "--html",
        help="Write HTML report to file"
    )

    args = parser.parse_args()

    try:
        with open(args.file, "r") as f:
            code = f.read()
    except Exception as e:
        print(f"ERROR: Could not read file: {e}", file=sys.stderr)
        sys.exit(2)

    judge = MultiAgentCodeJudge(model=args.model)
    result = judge.judge(code)

    # --- HTML report ---
    if args.html:
        write_html_report(result, args.file, args.model, args.html)
        if not args.ci:
            print(f"HTML report written to: {args.html}")

    # --- Output modes ---
    if args.json or args.ci:
        print(json.dumps(result, indent=2 if not args.ci else None))
    else:
        print("\n=== CLAUDE MULTI-AGENT CODE JUDGE ===\n")
        print("FILE:", args.file)
        print("MODEL:", args.model)
        print()
        print("OVERALL:", "PASS ✅" if result["overall_pass"] else "FAIL ❌")
        print("POLICY:", "PASS ✅" if result["policy_pass"] else "FAIL ❌")
        print("AVERAGE SCORE:", result["average_score"])
        print()

        if result["blocking_failures"]:
            print("BLOCKING FAILURES:", ", ".join(result["blocking_failures"]))
            print()

        for v in result["verdicts"]:
            print(f"[{v['agent'].upper()}]")
            print("PASS:", v["pass"])
            print("SCORE:", v["score"])
            print("SUMMARY:", v["summary"])
            if v["issues"]:
                print("ISSUES:")
                for i in v["issues"]:
                    print(" -", i)
            print("-" * 50)

    # --- CI EXIT CODE ---
    if not result["policy_pass"]:
        sys.exit(1)
    else:
        sys.exit(0)


if __name__ == "__main__":
    main()
