import datetime
from pathlib import Path


def generate_html_report(result: dict, file_path: str, model: str) -> str:
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    verdict_color = "#2ecc71" if result["policy_pass"] else "#e74c3c"
    verdict_text = "PASS" if result["policy_pass"] else "FAIL"

    agent_blocks = ""

    for v in result["verdicts"]:
        color = "#2ecc71" if v["pass"] else "#e74c3c"

        issues_html = ""
        if v["issues"]:
            issues_html = "<ul>" + "".join(
                f"<li>{issue}</li>" for issue in v["issues"]
            ) + "</ul>"
        else:
            issues_html = "<p class='muted'>No issues</p>"

        agent_blocks += f"""
        <div class="agent-card">
            <h3>{v['agent'].title()}</h3>
            <p><strong>PASS:</strong> <span style="color:{color}">{v['pass']}</span></p>
            <p><strong>SCORE:</strong> {v['score']}</p>
            <p><strong>SUMMARY:</strong> {v['summary']}</p>
            <div class="issues">
                <strong>ISSUES:</strong>
                {issues_html}
            </div>
        </div>
        """

    blocking_html = ""
    if result.get("blocking_failures"):
        blocking_html = "<ul>" + "".join(
            f"<li>{a}</li>" for a in result["blocking_failures"]
        ) + "</ul>"
    else:
        blocking_html = "<p class='muted'>None</p>"

    html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Claude Code Judge Report</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
            background: #f6f8fa;
            padding: 30px;
            color: #222;
        }}
        .container {{
            max-width: 900px;
            margin: auto;
            background: #fff;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 4px 14px rgba(0,0,0,0.08);
        }}
        h1 {{
            margin-top: 0;
        }}
        .verdict {{
            font-size: 22px;
            font-weight: bold;
            color: {verdict_color};
        }}
        .meta {{
            color: #666;
            font-size: 14px;
        }}
        .score {{
            font-size: 18px;
            margin-top: 10px;
        }}
        .agent-card {{
            border: 1px solid #e1e4e8;
            border-radius: 8px;
            padding: 15px 20px;
            margin-top: 20px;
        }}
        .agent-card h3 {{
            margin-top: 0;
        }}
        .issues {{
            margin-top: 10px;
        }}
        .muted {{
            color: #888;
        }}
        .footer {{
            margin-top: 40px;
            font-size: 13px;
            color: #888;
            text-align: center;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Claude Code Judge Report</h1>

        <p class="meta"><strong>File:</strong> {file_path}</p>
        <p class="meta"><strong>Model:</strong> {model}</p>
        <p class="meta"><strong>Generated:</strong> {now}</p>

        <p class="verdict">Policy Verdict: {verdict_text}</p>

        <p class="score"><strong>Average Score:</strong> {result['average_score']}</p>

        <h2>Blocking Failures</h2>
        {blocking_html}

        <h2>Agent Verdicts</h2>
        {agent_blocks}

        <div class="footer">
            Generated by Claude Multi-Agent Code Judge
        </div>
    </div>
</body>
</html>
"""
    return html


def write_html_report(result: dict, file_path: str, model: str, output_path: str):
    html = generate_html_report(result, file_path, model)
    Path(output_path).write_text(html, encoding="utf-8")
