name: "Gatekeeper"
description: "Deterministic code governance and enforcement"
author: "GatekeeperAI"

inputs:
  path:
    description: "Path to scan"
    required: false
    default: "."
  python-version:
    description: "Python version for pipx"
    required: false
    default: "3.11"
  github-token:
    description: "GitHub token for PR comments"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install pipx
      run: |
        python -m pip install --user pipx
        python -m pipx ensurepath
      shell: bash

    - name: Install gatekeeper
      run: |
        pipx install .
      shell: bash

    - name: Run gatekeeper
      id: gatekeeper
      run: |
        set +e
        ~/.local/bin/gatekeeper ${{ inputs.path }} > gatekeeper.out 2>&1
        echo "exit_code=$?" >> $GITHUB_OUTPUT
        set -e
      shell: bash

    - name: Post PR comment on failure
      if: steps.gatekeeper.outputs.exit_code != '0'
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        bash .github/actions/gatekeeper/post_comment.sh gatekeeper.out
      shell: bash

    - name: Fail job if gatekeeper failed
      if: steps.gatekeeper.outputs.exit_code != '0'
      run: exit 1
      shell: bash
